#
# Learn more at https://www.home-assistant.io/components/automation/
#
- alias: 'HASS RPi Low Disk Space Alert'
  trigger:
    - platform: numeric_state
      entity_id: sensor.disk_use_percent_
      above: 90
  action:
    - service: notify.notify
      data: 
        title: "HASS RPi Alert"
        message: "Low Disk Space > 10% Free"

################################################################
- alias: 'HASS RPi Low Memory Alert'
  trigger:
    - platform: numeric_state
      entity_id: sensor.memory_use_percent
      above: 90
  action:
    - service: notify.notify
      data: 
        title: "HASS RPi Alert"
        message: "Low Memory > 10% Free"

################################################################
- alias: 'Update Notification'
  trigger:
    platform: state
    entity_id: updater.updater
  action:
    service: notify.notify
    data:
      title: 'New HA release'
      message: 'Home Assistant {{states.updater.updater.state}} is now available...'

################################################################
- alias: 'HASS Start'
  trigger:
    platform: event
    event_type: homeassistant_start
  action:
    service: notify.notify
    data:
      message: 'HA started' 
# message:  'Home Assistant started: {{ as_timestamp(now()) | timestamp_custom("%b %d %X") }}'      

################################################################
- alias: 'HASS Stop'
  trigger:
    platform: event
    event_type: homeassistant_stop
  action:
    service: notify.notify
    data:
      message: 'HA stopped'  

################################################################
- alias: 'Backyard Light Timer'
  trigger:
    platform: state
    entity_id: switch.back_yard_lights
    to: 'on'
    for:
      minutes: 30
  action:
    service: notify.notify
    data:
      message: 'Backyard lights are on...'
################################################################
- alias: 'Garage Light Timer'
  trigger:
    platform: state
    entity_id: switch.garage_light
    to: 'on'
    for:
      minutes: 30
  action:
    service: notify.notify
    data:
      message: 'Garage lights are on...'
################################################################
- id: hass_theme
  alias: 'HASS Theme'
  initial_state: 'on'
  trigger: 
    - platform: state
      entity_id: input_select.hass_theme
  action:
    - service: frontend.set_theme
      data_template:
        name: "{{ states.input_select.hass_theme.state }}"
