title: My Home
# Include external resources
resources:
  # https://github.com/custom-cards/button-card
  - url: /local/button-card.js
    type: module
  # https://github.com/custom-components/custom_updater
  - url: /customcards/github/custom-cards/button-card.js?track=true
    type: module

# Optional background for all views. Check https://developer.mozilla.org/en-US/docs/Web/CSS/background for more examples.
#background: center / cover no-repeat url("/background.png") fixed
# Exclude entities from "Unused entities" view
#excluded_entities:
#  - weblink.router
views:
    # View tab title.
  - title: Home
    # Unique path for direct access /lovelace/${path}
    path: home
    icon: mdi:home
    # Cards
    cards:
      - type: "custom:button-card"
        entity: switch.den_table_lamp_tv
        name: TV Lamp
        #icon: midi:sofa
        #color_type: card
        color: auto

    # Title of the view. Will be used as the tooltip for tab icon
  - type: horizontal-stack
    title: Lights
    path: lights
    icon: mdi:home-assistant
    cards:
      - type: "custom:button-card"
        entity: switch.den_table_lamp_stairs
        name: Stairs Lamp
        #icon: midi:sofa
        color: auto
        styles:
          card:
            - height: 110px
            - width: 110px

      - type: "custom:button-card"
        entity: switch.den_table_lamp_tv
        name: TV Lamp
        #icon: midi:sofa
        #color_type: card
        color: auto
        #size: 25%
        styles:
          card:
            - height: 110px
            - width: 110px

      - type: "custom:button-card"
        entity: switch.front_door_light
        #label_template: >
        #  var bri = states['light.test_light'].attributes.brightness; 
        #  return 'Brightness: ' + (bri ? bri : '0') + '%';
        name: Front Door
        #icon: midi:sofa
        color: auto
        styles:
          card:
            - height: 110px
            - width: 110px

      - type: "custom:button-card"
        entity: switch.back_door_lights
        name: Back Door
        color: auto
        styles:
          card:
            - height: 110px
            - width: 110px

      - type: "custom:button-card"
        entity: binary_sensor.backdoor_sensor
        name: Back Door Motion
        #icon: midi:sofa
        color: auto
        styles:
          card:
            - height: 110px
            - width: 110px

      - type: "custom:button-card"
        entity: switch.back_yard_lights
        name: Back Yard
        #icon: midi:sofa
        color: auto
        styles:
          card:
            - height: 110px
            - width: 110px

      - type: "custom:button-card"
        entity: switch.garage_light
        name: Garage
        #icon: midi:sofa
        color: auto
        styles:
          card:
            - height: 110px
            - width: 110px

      - type: "custom:button-card"
        entity: switch.master_bedroom_table_lamp
        name: Master Bedroom
        #icon: midi:sofa
        color: auto
        styles:
          card:
            - height: 110px
            - width: 110px
